language: csharp
solution: AlgorithmParty.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore AlgorithmParty.sln
after_script:
  - nunit-console AlgorithmParty.Tests/bin/Release/AlgorithmParty.Tests.dll
